name: Pacakge
inputs:
  token:
    description: "Github token with package credentials"
    required: true
    default: ""
  user:
    description: "Github user with package credentials"
    required: true
    default: ""

runs:
  using: ubuntu-latest
  strategy:
    matrix:
      java: [ '8', '11', '17', '21' ]

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: ${{ matrix.java }}
        cache: 'maven'

    - name: Configure Maven settings
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<EOL
        <settings>
          <activeProfiles>
            <activeProfile>github</activeProfile>
          </activeProfiles>
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.GITHUB_TOKEN }}</password>
            </server>
          </servers>
        </settings>
        EOL

    - name: Publish package
      run: mvn --batch-mode deploy