name: PR

on:
  push:
    branches-ignore:
      - "main"
      - "master"

permissions:
  contents: read

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/lint_and_test.yml
