name: PR

on:
  push:
    branches-ignore:
      - "main"
      - "master"

permissions:
  contents: read

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/lint-and-test/action.yml
